apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "shared-data"
  namespace: "project"
spec:
  storageClassName: "local-storage-project"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
