apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "ping-pong"
spec:
  rules:
    - http:
        paths:
          - path: "/pingpong"
            pathType: "Prefix"
            backend:
              service:
                name: "ping-pong"
                port:
                  number: 1236
          - path: "/status"
            pathType: "Prefix"
            backend:
              service:
                name: "log-output"
                port:
                  number: 1234
