apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "log-output"
  namespace: "exercises"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "log-output"
  template:
    metadata:
      labels:
        app: "log-output"
    spec:
      securityContext:
        fsGroup: 10001
      volumes:
        - name: "shared-output"
          emptyDir: {}
      containers:
        - name: "log-output-writer"
          image: "registry:5111/log-output-writer"
          volumeMounts:
            - name: "shared-output"
              mountPath: "/app/files"
        - name: "log-output-server"
          image: "registry:5111/log-output-server"
          volumeMounts:
            - name: "shared-output"
              mountPath: "/app/files"
          env:
            - name: "PORT"
              value: "8090"
